### PR TITLE
Preserve `body` on request object passed to `willSendRequest`; fix `string` and `Buffer` body handling

### LINKED ISSUE #83: POST request body is undefined when use willSendRequest
path : packages/apollo-datasource-rest/src/RESTDataSource.ts line 210
issue : POST request body is undefined when use willSendRequest
current code :
```
    const modifiedRequest: WillSendRequestOptions = {
      ...request,
      // guarantee params and headers objects before calling `willSendRequest` for convenience
      params:
        request.params instanceof URLSearchParams
          ? request.params
          : new URLSearchParams(request.params),
      headers: request.headers ?? Object.create(null),
      body: undefined,
    };
```

change required :
```
    const modifiedRequest: WillSendRequestOptions = {
      ...request,
      // guarantee params and headers objects before calling `willSendRequest` for convenience
      params:
        request.params instanceof URLSearchParams
          ? request.params
          : new URLSearchParams(request.params),
      headers: request.headers ?? Object.create(null),
    };
```

actual behavior : when use willSendRequest which post method in any class extends RESTDataSource every post request have missing body
 
expected behavior : when use willSendRequest request body is the same as defined by user  
 

reproduce : create any class extends RESTDataSource, create anyone POST request and try to use willSendRequest method. Body in this request will be undefined

### PR DESCRIPTION
**Pull request by trevor-scheer**
The v4 update introduced multiple regressions w.r.t. the `modifiedRequest` object that I added.
1) `body` was no longer being added to the intermediary request object before calling `willSendRequest`
2) `modifiedRequest.body` was never being set in the case that the incoming body was a `string` or `Buffer`

This change resolves both by reverting to what we previously had in v3 (preserving the properties on the incoming request object). The types had to be updated accordingly. Due to how `path` is now handled in v4, the `willSendRequest` signature is now `(path, request)`.

I'm a bit disappointed in the complexity of the typings in here. We make multiple incremental refinements to the request object:
1) first by ensuring headers/params, effectively adding one level of `WithRequired` to our incoming request type
2) second by refining the `body` type to drop the `object` from the union since those are stringified

Our hooks expose the request object that we're building at various points in the construction of the request so these types are part of the public API - kind of confusing and difficult to name in ways that are simple and sensible.
i.e. `RequestWithHeadersAndParams` and `RequestWithHeadersAndParamsAndBodyIsCompatibleWithFetch`

Fixes #83

### CODE REVIEW

**Comment by trevor-scheer** [comment]
@marcin-zajac would you mind testing out the fix here and letting me know if it resolves the issue for you? Builds are in the codesandbox ci link (my most recent build at the time of writing this can be installed via `npm i https://pkg.csb.dev/apollographql/datasource-rest/commit/36c5b4ec/@apollo/datasource-rest`)

**Comment by trevor-scheer** [comment]
One drawback to this implementation: hooks get the stringified version of things, meaning they'll have to re-`JSON.parse()` the content if they're interested in it. We could optionally provide an additional argument (like `originalBody`) or something if that seems valuable.

**Comment by leonbe02** [comment]
@trevor-scheer Can you also include in this PR the ability to send `POST` requests with `Content-Type: application/x-www-form-urlencoded` with the body being a `string` ? Currently the code is ignoring the `body` if it is a url encoded form which is a very common use case for older APIs that don't use JSON.

**Comment by trevor-scheer** [comment]
@leonbe02 that sounds like a reasonable suggestion, but do you think it belongs with this PR for a particular reason? I think it's a separate concern which I'd be happy to address in a different PR unless you have an argument for these pieces of work being the same concern.

Opening a separate issue would be helpful for me if you don't mind. Please be as descriptive as possible. Are there any current workarounds you're employing?

**Comment by leonbe02** [comment]
I bring it up in this PR because this PR claims to resolve #83 which mentions the `application/x-www-form-urlencoded` bug and you're touching the same lines of code that would need to be updated to resolve the bug. Simply removing the `body: undefined` part of `modifiedRequest` would allow for the `body` to be a string and pass thru to the `fetch` function.

**Comment by trevor-scheer** [comment]
@leonbe02 let me know if the changes I've made match your expectation. For typing reasons, it's not as simple as passing the body through straight from the request object, but I can append it without serializing when it's a `string` which seems reasonable. Of the possible types (`undefined`, `object`, `Buffer`, `string`), these should all be accounted for now.

I added 2 commits: one with a test to show what was failing, and a second which implements the fix and brings the test to passing.

**Review by leonbe02 — APPROVED** [review]
Looks good, thanks for doing that!

**Comment by trevor-scheer** [comment]
Thanks for calling it out and taking the time to review 👍

**Comment by glasser** [comment]
didn't full review yet, but make sure to update the commit message with the second change that was added, and to write a changeset.

File: src/RESTDataSource.ts [hunk 1]
```diff
@@ -237,6 +228,19 @@ export abstract class RESTDataSource {
       } else if (!modifiedRequest.headers['content-type']) {
         modifiedRequest.headers['content-type'] = 'application/json';
       }
+    } else if (typeof request.body === 'string') {
```
Comment (glasser) [inline src/RESTDataSource.ts:231]: Shouldn't this just be `else` (ie, what about Buffer, etc)?
Also it seems like this is a HUGE bug in the existing code: string/Buffer bodies are just dropped?

Comment (glasser) [reply src/RESTDataSource.ts:231]: Yeah I think you should call this out more in the PR description/forthcoming changeset — that this fixes the use of string and Buffer bodies (and add a test for Buffer bodies) which was broken in v4 previously.

File: src/RESTDataSource.ts [hunk 2]
```diff
@@ -237,6 +228,19 @@ export abstract class RESTDataSource {
...
+      modifiedRequest.body = request.body;
+    }
+
+    if (this.willSendRequest) {
+      await this.willSendRequest(modifiedRequest);
```
Comment (glasser) [inline src/RESTDataSource.ts:236]: I'm not really sure I understand the purported semantics of willSendRequest (even ignoring this stuff, it's called weirdly early compared to the caching, so the doc in the README seems wrong). It seems like maybe keeping compatibility with the past (ie, moving it higher) could be reasonable — maybe people depend on being able to poke around for fields in the body in it? I dunno, it's an oddly named hook with odd semantics.

File: src/RESTDataSource.ts [hunk 3]
```diff
@@ -46,7 +39,14 @@ export interface RequestWithBody extends Omit<RequestOptions, 'body'> {
   body?: FetcherRequestInit['body'] | object;
 }
 
-type DataSourceRequest = GetRequest | RequestWithBody;
+export type DataSourceRequest = GetRequest | RequestWithBody;
+
+export type AugmentedRequest = (
```
[the remark this answers is not in the document]
Comment (trevor-scheer) [reply src/RESTDataSource.ts:44]: Open to naming suggestion here. We have these request types that are all _very_ similar but their distinction is also important since each incremental difference is exposed to the API surface area.

File: src/index.ts [hunk 4]
```diff
@@ -1,5 +1,5 @@
 export {
   RESTDataSource,
   RequestOptions,
-  WillSendRequestOptions,
+  AugmentedRequest,
```
Comment (trevor-scheer) [inline src/index.ts:4]: The name change here alone makes this a v5 change. Could continue exporting this as an alias, but maybe the naming is still up in the air anyway.

File: .changeset/cuddly-cars-sparkle.md [hunk 5]
```diff
@@ -0,0 +1,10 @@
+---
+'@apollo/datasource-rest': patch
+---
+
+The v4 update introduced multiple regressions w.r.t. the intermediary `modifiedRequest` object that was added.
```
Comment (glasser) [inline .changeset/cuddly-cars-sparkle.md:5]: I think this changeset should be more clear that this is about `willSendRequest`?

File: .changeset/cuddly-cars-sparkle.md [hunk 6]
```diff
@@ -0,0 +1,10 @@
...
+
+1. The `body` was no longer being added to the intermediary request object before calling `willSendRequest`
+2. `modifiedRequest.body` was never being set in the case that the incoming body was a `string` or `Buffer`
+
+This change resolves both by reverting to what we previously had in v3 (preserving the properties on the incoming request object). The types have been updated accordingly.
```
Comment (glasser) [inline .changeset/cuddly-cars-sparkle.md:10]: This is true at a high level, though concretely it might imply "the arguments to willSendRequest match v3" which isn't really true (eg, the *number* of arguments has changed, or maybe should?)

File: src/RESTDataSource.ts [hunk 7]
```diff
@@ -205,71 +208,74 @@ export abstract class RESTDataSource {
...
-      body: undefined,
+        incomingRequest.params instanceof URLSearchParams
+          ? incomingRequest.params
+          : this.urlSearchParamsFromRecord(incomingRequest.params),
+      headers: incomingRequest.headers ?? Object.create(null),
     };
 
     if (this.willSendRequest) {
-      await this.willSendRequest(modifiedRequest);
+      await this.willSendRequest(augmentedRequest);
```
Comment (glasser) [inline src/RESTDataSource.ts:224]: In v3 this effectively included `path` (because it was part of the sole argument to `fetch`) so we should restore that here too?  (Or make AugmentedRequest even more complex by smushing `path` onto it too

File: src/RESTDataSource.ts [hunk 8]
```diff
@@ -205,71 +208,74 @@ export abstract class RESTDataSource {
...
+    // `string`, `Buffer`, and `undefined` are passed through up above as-is.
     if (
-      request.body !== undefined &&
-      request.body !== null &&
-      (request.body.constructor === Object ||
-        Array.isArray(request.body) ||
-        ((request.body as any).toJSON &&
-          typeof (request.body as any).toJSON === 'function'))
+      augmentedRequest.body != null &&
+      (augmentedRequest.body.constructor === Object ||
```
Comment (glasser) [inline src/RESTDataSource.ts:238]: Just to make sure I've got it straight, this conditional is planned to be changed but in the other PR right?

File: src/RESTDataSource.ts [hunk 9]
```diff
@@ -205,71 +208,74 @@ export abstract class RESTDataSource {
...
+        augmentedRequest.headers = { 'content-type': 'application/json' };
+      } else if (!augmentedRequest.headers['content-type']) {
+        augmentedRequest.headers['content-type'] = 'application/json';
       }
     }
 
-    const cacheKey = this.cacheKeyFor(url, modifiedRequest);
+    // At this point we know the `body` is a `string`, `Buffer`, or `undefined`
+    // (not possibly an `object`).
+    const outgoingRequest = <RequestOptions>augmentedRequest;
```
Comment (glasser) [inline src/RESTDataSource.ts:254]: unfamiliar syntax to me

File: src/RESTDataSource.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (glasser) [reply src/RESTDataSource.ts:47]: Could just leave it as WIllSendRequestOptions...  not sure.

File: src/RESTDataSource.ts (hunk 8 above)
Comment (trevor-scheer) [reply src/RESTDataSource.ts:238]: Yes

File: .changeset/cuddly-cars-sparkle.md (hunk 5 above)
Comment (trevor-scheer) [reply .changeset/cuddly-cars-sparkle.md]: Not sure I agree, up above we agreed that the `string | Buffer` problem was a glaring regression. In any case, I've updated the changeset to call out both separately and a bit more clearly.

File: .changeset/cuddly-cars-sparkle.md (hunk 6 above)
Comment (trevor-scheer) [reply .changeset/cuddly-cars-sparkle.md]: Updated signature to `(path, augmentedRequest)` and called out in the changeset

File: src/RESTDataSource.ts (hunk 7 above)
Comment (trevor-scheer) [reply src/RESTDataSource.ts]: Agreed

**Comment by trevor-scheer** [comment]
@glasser I can't find out how to reply to your comment about the type name.

Worth mentioning this type is also part of the `resolveURL` signature, so it's used for both hooks. Maybe `IntermediaryRequest` makes sense? We now have the concept (in code) of an incoming vs. outgoing request.

File: src/RESTDataSource.ts [hunk 10]
```diff
@@ -48,6 +41,16 @@ export interface RequestWithBody extends Omit<RequestOptions, 'body'> {
 
 type DataSourceRequest = GetRequest | RequestWithBody;
 
+// While tempting, this union can't be reduced / factored out to just
+// Omit<WithRequired<GetRequest | RequestWithBody, 'headers'>, 'params'> & { params: URLSearchParams }
+// TS loses its ability to discriminate against the method (and its consequential `body` type)
+export type AugmentedRequest = (
```
Comment (glasser) [inline src/RESTDataSource.ts:47]: Might be worth a comment that the point here is basically, this is like DataSourceRequest but with `headers` and `params` normalized for convenience in your callbacks.

BTW unrelated but it seems like `method` shouldn't be optional in GetRequest/RequestWithBody?

File: README.md [hunk 11]
```diff
@@ -207,7 +207,7 @@ class PersonalizationAPI extends RESTDataSource {
     super();
   }
 
-  override willSendRequest(request: WillSendRequestOptions) {
+  override willSendRequest(request: AugmentedRequest) {
```
Comment (glasser) [inline README.md:210]: Several calls to willSendRequest in the README need the new argument. Also the wording in the `willSendRequest` section could be adjusted for accuracy (and maybe link to the "Intercepting fetches" section)

**Review by glasser — APPROVED** [review]
Think this looks good modulo these concerns — lmk if you want me to take another look after any adjustments.

File: src/RESTDataSource.ts [hunk 12]
```diff
@@ -41,9 +41,16 @@ export interface RequestWithBody extends Omit<RequestOptions, 'body'> {
 
 type DataSourceRequest = GetRequest | RequestWithBody;
 
-// While tempting, this union can't be reduced / factored out to just
-// Omit<WithRequired<GetRequest | RequestWithBody, 'headers'>, 'params'> & { params: URLSearchParams }
-// TS loses its ability to discriminate against the method (and its consequential `body` type)
+/**
+ * While tempting, this union can't be reduced / factored out to just
```
Comment (glasser) [inline src/RESTDataSource.ts:45]: this part probably doesn't deserve to be in the `/**` javadoc

File: README.md [hunk 13]
```diff
@@ -105,7 +105,11 @@ By default, `RESTDatasource` uses the full request URL as the cache key. Overrid
 For example, you could use this to use header fields as part of the cache key. Even though we do validate header fields and don't serve responses from cache when they don't match, new responses overwrite old ones with different header fields.
 
 ##### `willSendRequest`
-This method is invoked just before the fetch call is made. If a `Promise` is returned from this method it will wait until the promise is completed to continue executing the request.
+This method is invoked immediately after `fetch` is called (or any of the
```
Comment (glasser) [inline README.md:108]: unfortunately `fetch` is a private method so this is confusing (and probably still sounds like it means calling the `fetcher` which isn't what it is).

Not sure what the best way of expressing this is.  Probably more just like "This method is called at the beginning of processing each request" or something?

File: .changeset/tidy-spoons-nail.md [hunk 14]
```diff
@@ -0,0 +1,8 @@
+---
+'@apollo/datasource-rest': patch
+---
+
+`string` and `Buffer` bodies are now correctly included on the outgoing request.
+Due to a regression in v4, they were ignored and never appended to the `body`.
```
Comment (glasser) [inline .changeset/tidy-spoons-nail.md:6]:
```suggestion
Due to a regression in v4, they were ignored and never sent as the `body`.
```

maybe? nothing is really being appended
